name: Release devcontainer features

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  test-features:
    uses: ./.github/workflows/test-features.yml

  publish:
    needs: test-features
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish Features
        uses: devcontainers/action@v1.4.3
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          imageName: "ghcr.io/${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"