name: Test Features

on:
  workflow_call:
    inputs:
      tests:
        type: string
        default: ""

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.set-matrix.outputs.tests }}

    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          if [ -n "${{ inputs.tests }}" ]; then
            echo "tests=${{ inputs.tests }}" >> "$GITHUB_OUTPUT"
          else
            files=$(ls -1 src/*/test.sh | jq -R -s -c '
              split("\n")[:-1]
              | map({
                  path: .,
                  name: (split("/")[1]),
                  script: ("bash \"" + . + "\"")
                })
            ')
            echo "tests=$files" >> "$GITHUB_OUTPUT"
          fi

  test:
    needs: discover
    runs-on: ubuntu-latest

    name: test ${{ matrix.test.name }}

    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.discover.outputs.tests) }}

    steps:
      - uses: actions/checkout@v4

      - name: Run feature test in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: ${{ matrix.test.script }}